---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
      day: monday
      time: '10:00'
      timezone: Asia/Singapore
    reviewers:
      - 'nicholas5538'
      - 'Rychua002'
    open-pull-requests-limit: 1
    pull-request-branch-name:
      separator: '-'

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '10:00'
      timezone: Asia/Singapore
    reviewers:
      - 'nicholas5538'
      - 'Rychua002'
    ignore:
      - dependency-name: '@types/*'
      - dependency-name: 'eslint-plugin-n'
        versions: ['16.x']
    commit-message:
      prefix: 'Yarn Prod'
      prefix-development: 'Yarn Dev'
      include: scope
    open-pull-requests-limit: 3
    pull-request-branch-name:
      separator: '-'
