env:
  browser: true
  es2021: true
  node: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/eslint-recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:@tanstack/eslint-plugin-query/recommended'
overrides: []
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 'latest'
  sourceType: 'module'
plugins:
  - promise
  - '@typescript-eslint'
  - '@tanstack/query'
rules:
  quotes:
    - error
    - single
  semi:
    - error
    - always
  comma-dangle:
    - error
    - always-multiline
  no-unused-vars: error
  promise/always-return: error
  promise/no-return-wrap: error
  promise/param-names: error
  promise/catch-or-return: error
  promise/no-callback-in-promise: warn
  '@tanstack/query/exhaustive-deps': error
root: true
