version: '3.8'
services:
  devmode:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: vite-dev
    command: pnpm run dev --host 0.0.0.0
    restart: always
    ports:
      - '5173:5173'
    volumes:
      - .:/app
      - /app/node_modules
