---
name: Push development image
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  Push-to-docker-hub:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3.6.0

      - name: Try to build image
        run: |
          docker build --platform linux/amd64 --no-cache --compress \
          --rm -t vite-build --target build .
