---
name: Test build
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  Build:
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.6.0

      - name: Write secrets to env file
        run: |
          echo "VITE_API_BASE_URL=${{ secrets.VITE_API_BASE_URL }}" > .env.production

      - name: Build Docker image
        run: docker build --no-cache -t build-app --target build .

      - name: Run Docker container
        run: docker run --env-file .env.production --rm --name run-build-test build-app
