---
name: Build development image
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  Push-to-docker-hub:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0

      - name: Docker - build dev image
        run: |
          docker build --platform linux/amd64 --no-cache --compress \
          --rm -t vite-build --target build .

      - name: Approve a PR
        if: github.actor == 'dependabot[bot]'
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
