---
name: Push development image
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  Push-to-docker-hub:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3.6.0

      - name: Login to Docker Hub
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build --platform linux/amd64 --compress -t fp-voucher-fe-dev --target dev .
          docker tag fp-voucher-fe-dev:latest $DOCKERHUB_USERNAME/fp-voucher-fe-dev:latest
          docker push $DOCKERHUB_USERNAME/fp-voucher-fe-dev:latest
