---
name: Firebase Production Deploy

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.4.0
        with:
          version: 8.7.0

      - name: Use Node.js 18
        uses: actions/setup-node@v3.8.1
        with:
          node-version: 18
          cache: 'pnpm'
          cache-dependency-path: 'pnpm-lock.yaml'

      - name: Install project dependencies
        run: pnpm i --prod --frozen-lockfile

      - name: Build project
        run: pnpm run build

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_VOUCHER }}'
          channelId: live
          projectId: fp-capstone-voucher-78842
