---
name: Deploy to production

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  Build-image-and-deploy:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3.6.0

      - name: Login to Docker Hub
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Write secrets to env file
        run: |
          echo "VITE_API_BASE_URL=${{ secrets.VITE_API_BASE_URL }}" > .env.production

      - name: Build and push Docker image
        run: |
          docker build --platform linux/amd64 --compress -t fp-voucher-fe .
          docker tag fp-voucher-fe:latest $DOCKERHUB_USERNAME/fp-voucher-fe:latest
          docker push $DOCKERHUB_USERNAME/fp-voucher-fe:latest

      - name: Trigger Render deployment
        run: curl -X POST -d {} "${{ secrets.DEPLOY_HOOK }}"