---
name: Firebase Preview Deployment
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  Deploy-Preview:
    if: ${{ (github.actor != 'dependabot[bot]') && (github.event.pull_request.head.repo.full_name == github.repository) }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - name: Install project dependencies
        run: yarn install --immutable

      - name: Build project
        run: yarn build

      - name: Deploy to Preview channel
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_VOUCHER }}'
          projectId: fp-capstone-voucher-78842
          expires: 7d
          channelId: development
